refType={

'article-journal':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Number':'number',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'bill':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'Code Pages':'page',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Legislative Body':'publisher',
  'Note':'note',
  'Number':'number',
  'Publication':'container-title',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'book':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'chapter':{
  'Abstract':'abstract',
  'Book':'container-title',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'paper-conference':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Proc. Title':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'entry-encyclopedia':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Encyclopedia':'container-title',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'motion_picture':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Distributor':'publisher',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'speech':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'article-magazine':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'article-newspaper':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume'
},

'patent':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Issuer':'publisher',
  'Note':'note',
  'Number':'number',
  'Pages':'page',
  'Short Title':'shortTitle',
  'Source':'container-title',
  'Title':'title',
  'Volume':'volume'
},

'report':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Number':'number',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Series Volume':'volume',
  'Short Title':'shortTitle',
  'Title':'title',
},

'legislation':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Short Title':'shortTitle',
  'Source':'publisher',
  'Statute Number':'number',
  'Title':'title',
  'Volume':'volume',
},

'thesis':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume',
},

'broadcast':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Distributor':'publisher',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume',
},

'webpage':{
  'Abstract':'abstract',
  'Chapter':'chapter-number',
  'City':'publisher-place',
  'DOI':'DOI',
  'Date Accessed':'accessed',
  'Edition':'edition',
  'Genre':'genre',
  'ISBN':'ISBN',
  'Issue':'issue',
  'Note':'note',
  'Pages':'page',
  'Publication':'container-title',
  'Publisher':'publisher',
  'Revision Number':'number',
  'Short Title':'shortTitle',
  'Title':'title',
  'Volume':'volume',
}
}